version: "3"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: algunpassword
      POSTGRES_DB: AnyList
    container_name: anylist
    volumes:
      - ./postgres:/var/lib/postgresql/data
