fullnameOverride: #{name}

global:
  environment: #{environment}
  nodeEnv: #{nodeEnv}
  host: "#{host}"
  dockerRegistry: #{docker_registry}
  requestsCPURequest: #{requestsCPURequest}
  requestsMemoryRequest: #{requestsMemoryRequest}
  requestsMemoryLimit: #{requestsMemoryLimit}
  namespace: #{namespace}

  attachment:
    name: #{name}
    replicaCount: #{replicaCount}
    image:
      tag: #{tag}
      pullPolicy: #{pullPolicy}
    logLevel: #{logLevel}
    resources: #{resources}
    nodeSelector: #{nodeSelector}
    tolerations: #{tolerations}
    affinity: #{affinity}
    mongoHost: #{mongo_host}
    mongoPort: #{mongo_port}
    mongoName: #{mongo_name}
    mongoUser: #{mongo_user}
    mongoPassword: #{mongo_password}
    azResourceGroup: #{app_resource_group_name}
    azAccountName: #{app_storage_account_name}
    azAccountKey: #{app_storage_account_key}
    azAccountUri: #{app_storage_account_uri}
    azPVName: #{app_persistent_volume_name}
    azPVCapacity: #{app_persistent_volume_capacity}
    azPVCName: #{app_persistent_volume_claim_name}
    azPVReclaimPolicy: #{app_persistent_volume_reclaim_policy}
    azPVHandle: #{app_persistent_volume_handle}
    azPVStorageAccount: #{app_persistent_volume_storage_account}
    azPVContainer: #{app_persistent_volume_container}
    azContainerNamePermanent: #{app_storage_container_permanent}
    azContainerNameTemporary: #{app_storage_container_temporary}
    azContainerNameDeleted: #{app_storage_container_deleted}
    port: #{attachment_port}
    enableHttpLogger: #{enableHttpLogger}
    types: #{attachment_types}
    size: #{attachment_size}
    kafkaBrokers: #{app_kafka_brokers}
    kafkaSaslSecretKey: #{app_kafka_sasl_secret_key}
    kafkaGroupId: #{app_kafka_group_id}
    kafkaHasSsl: #{app_kafka_has_ssl}
    kafkaSaslApiKey: #{app_kafka_sasl_api_key}
    kafkaEventDeletedRecordTopic: #{app_kafka_event_deleted_record_topic}
    kafkaEventSavedRecordTopic: #{app_kafka_event_saved_record_topic}
    sbConnection: #{app_service_bus_connection}
    sbTopic: #{app_service_bus_file_move_topic}
    sbFileMoveNotificationTopic: #{app_service_bus_file_move_notification_topic}
    sbScanStatusTopic: #{app_service_bus_scan_status_topic}
    sbFileMoveNotificationSubscription: #{app_service_bus_file_move_notification_subscription_name}
    sbFileScanStatusSubscription: #{app_service_bus_scan_status_subscription_name}
    sbMaxRetryAttemps: #{app_service_bus_max_retry_attemps}
    sbRetryDelayMS: #{app_service_bus_retry_delay_ms}
