fullnameOverride: app-nest

global:
  requestsCPURequest: 0.2
  requestsMemoryRequest: 200M
  requestsMemoryLimit: 250M
  namespace: default

  appNest:
    name: app-nest
    replicaCount: 3
    image:
      tag: main
      pullPolicy: #{pullPolicy}
    resources: {}
    nodeSelector: {}
    tolerations: {}
    affinity: {}
    port: 3000
    state: dev
    dbHost: 6.tcp.ngrok.io
    dbPort: 15028
    dbUsername: postgres
    dbPassword: algunpassword
    dbName: AnyList
    jwtSecret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.cThIIoDvwdueQB468K5xDc5633seEFoqwxjF_xSJyQQ
