fullnameOverride: app-nest

global:
  requestsCPURequest: 0.01
  requestsMemoryRequest: 80M
  requestsMemoryLimit: 100M
  namespace: default

  appNest:
    name: app-nest
    replicaCount: 1
    image:
      tag: latest
      pullPolicy: #{pullPolicy}
    resources: {}
    nodeSelector: {}
    tolerations: {}
    affinity: {}
    port: 3000
    state: dev
    dbHost: localhost
    dbPort: 5432
    dbUsername: postgres
    dbPassword: algunpassword
    dbName: AnyList
    jwtSecret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.cThIIoDvwdueQB468K5xDc5633seEFoqwxjF_xSJyQQ
