apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.appNest.fullname" . }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "app.appNest.fullname" . }}
    app.kubernetes.io/instance: app-nest
  ports:
    - name: app-nest
      port: 80
      targetPort: 3000
